# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["BinaryVixen899"]
description = "A quick [site or terminal prompt, maybe both!] that tells you who is fronting!"
language = "rust"
manifest_version = 2
name = "WhoisFrontingAtEdge"
service_id = ""
[backends]
    [origin_0]
        url = "https://api.pluralkit.me"
[local_server]
    [local_server.backends]
        [local_server.backends.origin_0]
            url = "https://api.pluralkit.me" 
